//
// Created by Zing Fong on 2022/5/25.
//

#ifndef LOOSECOUPLED_SRC_SINSTK_SINS_LOOSE_COUPLED_H
#define LOOSECOUPLED_SRC_SINSTK_SINS_LOOSE_COUPLED_H


class SinsLooseCoupled
{

};


#endif //LOOSECOUPLED_SRC_SINSTK_SINS_LOOSE_COUPLED_H
