//
// Created by Zing Fong on 2022/5/25.
//

#ifndef LOOSECOUPLED_SRC_SINSTK_SINS_MECHANIZATION_H
#define LOOSECOUPLED_SRC_SINSTK_SINS_MECHANIZATION_H


class SinsMechanization
{

};


#endif //LOOSECOUPLED_SRC_SINSTK_SINS_MECHANIZATION_H
