//
// Created by Zing Fong on 2022/5/25.
//

#ifndef LOOSECOUPLED_SRC_SINSTK_SINS_FILE_STREAM_H
#define LOOSECOUPLED_SRC_SINSTK_SINS_FILE_STREAM_H


class SinsFileStream
{

};


#endif //LOOSECOUPLED_SRC_SINSTK_SINS_FILE_STREAM_H
