//
// Created by Zing Fong on 2022/5/25.
//

#ifndef LOOSECOUPLED_SRC_GNSSTK_GNSS_FILE_STREAM_H
#define LOOSECOUPLED_SRC_GNSSTK_GNSS_FILE_STREAM_H


class GnssFileStream
{

};


#endif //LOOSECOUPLED_SRC_GNSSTK_GNSS_FILE_STREAM_H
